### ISSUE TITLE
Error Again

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/ReportSystemNK#2]
Same issue with #1 

22:04:37 [FATAL] "cn.nukkit.event.player.PlayerFormRespondedEvent" 이벤트를 "ReportSystem v1.0-SNAPSHOT"에 전달할 수 없습니다: net.llamadevelopment.reportsystem.listeners.FormListener에서의 null
22:04:37 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2591) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
        at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2099) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at net.llamadevelopment.reportsystem.listeners.FormListener.on(FormListener.java:144) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 16 more

Is this plugin conflict with other Form plugins?

**Comment by Mundschutziii** [comment]
Hm... Das könnte tatsächlich sein. Ich werde mir einen Fix dafür überlegen.

**Comment by Mundschutziii** [comment]
Hmm... This could be real. I'll think of a fix for it.

**Comment by good777LUCKY** [comment]
Thank you!

**Comment by good777LUCKY** [comment]
I think it is conflicting with this plugin.
https://github.com/FoxValleyMC/FormAPI

**Comment by Mundschutziii** [comment]
I can't exactly define the error.There will be a recode for this system in 2-3 months, because it contains obsolete and unperformant elements. Then I think the bug should be fixed!
